name: thinking-in-types
version: "0.1.0.0"
category: "learning"
author: "Yuriy Lazarev"
maintainer: unisay@users.noreply.github.com
copyright: "Yuriy Lazarev"
github: "unisay/thinking-in-types"
extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wimplicit-prelude
- -Wtabs
- -Wmissing-local-signatures
- -fhelpful-errors

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators

dependencies:
- base
- protolude

_common-deps: &common-deps
  - exceptions
  - protolude
  - text

library:
  source-dirs: src
  exposed-modules:
  - Ex_1_4
  - Ex_2_4
  - Ex_3_1
  dependencies: *common-deps

internal-libraries:
  thinking-in-types-internal:
    source-dirs: src
    exposed-modules:
    - Preamble
    dependencies: *common-deps

tests:
  spec:
    main: Main
    source-dirs:
    - test
    dependencies:
    - thinking-in-types-internal
    - hedgehog
    ghc-options:
    - -threaded
